networks:
  default:
    external:
      name: roboshop
services:
  # docker run -d --name mongodb --network=roboshop mongodb:1
  mongodb:
    image: mongodb:1
    container_name: mongodb
  catalogue:
    image: catalogue:1
    container_name: catalogue
    depends_on:
    - mongodb

  web:
    image: web:1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - cart
      - user
  user:
    image: user:1
    container_name: user
    depends_on:
      - mongodb
      - redis

  cart: 
    image: cart:1
    container_name: cart
    depends_on:
      - redis
      - catalogue
  redis:
    image: redis
    container_name: redis
